/**
 * Git Hooks Module
 * @module git/hooks
 */

import fs from 'fs/promises';
import path from 'path';
import { fileExists, writeFile } from '../utils/fs.js';

const PRE_COMMIT_HOOK_CONTENT = `#!/bin/sh
# fix-commit pre-commit hook
# Automatically generated by fix-commit

npx fix-commit scan --quiet
if [ $? -ne 0 ]; then
  echo "🔒 fix-commit: Secrets detected in staged files! Commit blocked."
  echo "💡 Run 'npx fix-commit scan' for details or 'npx fix-commit migrate' to fix."
  exit 1
fi
`;

/**
 * Setup Git pre-commit hook
 * @param {string} projectRoot - Project root directory
 * @returns {Promise<string>} Hook path
 */
export async function setupGitHooks(projectRoot) {
  const hooksDir = path.join(projectRoot, '.git', 'hooks');

  try {
    await fs.mkdir(hooksDir, { recursive: true });
  } catch (error) {
    throw new Error(`Failed to create git hooks directory: ${error.message}`);
  }

  const hookPath = path.join(hooksDir, 'pre-commit');

  await writeFile(hookPath, PRE_COMMIT_HOOK_CONTENT);

  try {
    await fs.chmod(hookPath, 0o755);
  } catch {
    // Ignore chmod errors on Windows
  }

  return hookPath;
}

/**
 * Remove Git pre-commit hook
 * @param {string} projectRoot - Project root directory
 * @returns {Promise<boolean>}
 */
export async function removeGitHooks(projectRoot) {
  const hookPath = path.join(projectRoot, '.git', 'hooks', 'pre-commit');
  if (await fileExists(hookPath)) {
    await fs.unlink(hookPath);
    return true;
  }
  return false;
}

export default {
  setupGitHooks,
  removeGitHooks
};
